#export CROSS_COMPILE=arm-linux-gnueabihf-
export CROSS_COMPILE=/opt/gcc-linaro-6.3.1-2017.02-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-
CC = $(CROSS_COMPILE)gcc

SRC  := $(wildcard *.c)
OBJ  := $(SRC:%.c=%.o)
.PHONY : clean all

all:
	$(CC) $(CFLAGS) $(SRC) -o ./ge2d_feature_test.a

clean:
	rm ge2d -f
	rm *.o
